-- begin PAYTHATRENT_TENANT
create unique index IDX_PAYTHATRENT_TENANT_UNIQ_PASSPORT_NUMBER on PAYTHATRENT_TENANT (PASSPORT_NUMBER)^
create unique index IDX_PAYTHATRENT_TENANT_UNIQ_IDENTIFICATION_NUMBER on PAYTHATRENT_TENANT (IDENTIFICATION_NUMBER)^
create unique index IDX_PAYTHATRENT_TENANT_UNIQ_EMAIL on PAYTHATRENT_TENANT (EMAIL)^
-- end PAYTHATRENT_TENANT
-- begin PAYTHATRENT_BANK_DETAILS
create unique index IDX_PAYTHATRENT_BANK_DETAILS_UNIQ_BANK_ID on PAYTHATRENT_BANK_DETAILS (BANK_ID)^
-- end PAYTHATRENT_BANK_DETAILS
-- begin PAYTHATRENT_LAND_LORD
create unique index IDX_PAYTHATRENT_LAND_LORD_UNIQ_EMAIL on PAYTHATRENT_LAND_LORD (EMAIL)^
-- end PAYTHATRENT_LAND_LORD
